import json
import os
from datetime import datetime
from io import BytesIO

from PIL import Image
from pptx import Presentation
from pptx.enum.pptx import PP_TRANSITION_SPEED
from pptx.util import Emu, Inches


# Transition type mapping — python-pptx exposes transition via slide.transition
# We set speed and advance timing; transition type defaults to "fade" via XML.
_TRANSITION_SPEEDS = {
    "slow": PP_TRANSITION_SPEED.SLOW,
    "medium": PP_TRANSITION_SPEED.MEDIUM,
    "fast": PP_TRANSITION_SPEED.FAST,
}


def _set_slide_transition(slide, transition_cfg: dict | None) -> None:
    """Apply transition settings to a slide."""
    if not transition_cfg:
        return
    try:
        trans = slide.slide_layout.slide_master.slide_layouts[0]  # noqa: F841
        # Use the slide's transition property directly
        slide_transition = slide.transition
        speed = transition_cfg.get("speed", "medium")
        slide_transition.speed = _TRANSITION_SPEEDS.get(speed, PP_TRANSITION_SPEED.MEDIUM)
        advance_seconds = transition_cfg.get("advance_after_seconds")
        if advance_seconds and isinstance(advance_seconds, (int, float)):
            slide_transition.advance_on_click = True
            slide_transition.advance_after = int(advance_seconds * 1000)
    except Exception:
        pass  # Transitions are best-effort; don't fail the whole PPT


def _set_presentation_metadata(prs: Presentation, plan: dict) -> None:
    """Set presentation metadata from plan."""
    core = prs.core_properties
    core.title = plan.get("title", "")
    core.author = plan.get("author", "MedrixFlow")
    core.subject = plan.get("subject", plan.get("title", ""))
    core.comments = f"Generated by MedrixFlow on {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    keywords = plan.get("keywords")
    if keywords:
        core.keywords = keywords if isinstance(keywords, str) else ", ".join(keywords)


def _fit_image_cover(img_width: int, img_height: int, slide_w_emu: int, slide_h_emu: int):
    """Cover mode: scale image to fill slide completely, cropping overflow."""
    img_aspect = img_width / img_height
    slide_aspect = slide_w_emu / slide_h_emu

    if img_aspect > slide_aspect:
        # Image wider than slide — fit height, crop width
        new_h = slide_h_emu
        new_w = int(slide_h_emu * img_aspect)
        left = -(new_w - slide_w_emu) // 2
        top = 0
    else:
        # Image taller than slide — fit width, crop height
        new_w = slide_w_emu
        new_h = int(slide_w_emu / img_aspect)
        left = 0
        top = -(new_h - slide_h_emu) // 2

    return Emu(left), Emu(top), Emu(new_w), Emu(new_h)


def _fit_image_contain(img_width: int, img_height: int, slide_w_emu: int, slide_h_emu: int):
    """Contain mode: scale image to fit within slide, letterboxing if needed."""
    img_aspect = img_width / img_height
    slide_aspect = slide_w_emu / slide_h_emu

    if img_aspect > slide_aspect:
        new_w = slide_w_emu
        new_h = int(slide_w_emu / img_aspect)
        left = 0
        top = (slide_h_emu - new_h) // 2
    else:
        new_h = slide_h_emu
        new_w = int(slide_h_emu * img_aspect)
        left = (slide_w_emu - new_w) // 2
        top = 0

    return Emu(left), Emu(top), Emu(new_w), Emu(new_h)


def generate_ppt(
    plan_file: str,
    slide_images: list[str],
    output_file: str,
) -> str:
    """
    Generate a PowerPoint presentation from slide images.

    Args:
        plan_file: Path to JSON file containing presentation plan
        slide_images: List of paths to slide images in order
        output_file: Path to output PPTX file

    Returns:
        Status message
    """
    # Load presentation plan
    with open(plan_file, "r", encoding="utf-8") as f:
        plan = json.load(f)

    # Determine slide dimensions based on aspect ratio
    aspect_ratio = plan.get("aspect_ratio", "16:9")
    if aspect_ratio == "16:9":
        slide_width = Inches(13.333)
        slide_height = Inches(7.5)
    elif aspect_ratio == "4:3":
        slide_width = Inches(10)
        slide_height = Inches(7.5)
    else:
        slide_width = Inches(13.333)
        slide_height = Inches(7.5)

    # Create presentation with specified dimensions
    prs = Presentation()
    prs.slide_width = slide_width
    prs.slide_height = slide_height

    # Set metadata
    _set_presentation_metadata(prs, plan)

    # Image fit mode: "cover" (fill, crop overflow) or "contain" (fit, letterbox)
    fit_mode = plan.get("image_fit", "cover")
    fit_fn = _fit_image_cover if fit_mode == "cover" else _fit_image_contain

    # Transition config (applied to all slides)
    transition_cfg = plan.get("transition")

    # Get blank layout
    blank_layout = prs.slide_layouts[6]  # Blank layout

    # Add each slide image
    slides_info = plan.get("slides", [])

    for i, image_path in enumerate(slide_images):
        if not os.path.exists(image_path):
            return f"Error: Slide image not found: {image_path}"

        slide = prs.slides.add_slide(blank_layout)

        # Apply transition
        _set_slide_transition(slide, transition_cfg)

        # Load and process image
        with Image.open(image_path) as img:
            if img.mode in ("RGBA", "P"):
                img = img.convert("RGB")

            img_width, img_height = img.size
            slide_w_emu = int(slide_width)
            slide_h_emu = int(slide_height)

            left, top, width, height = fit_fn(img_width, img_height, slide_w_emu, slide_h_emu)

            # Save processed image to bytes
            img_bytes = BytesIO()
            img.save(img_bytes, format="JPEG", quality=95)
            img_bytes.seek(0)

            slide.shapes.add_picture(img_bytes, left, top, width, height)

        # Add speaker notes if available in plan
        if i < len(slides_info):
            slide_info = slides_info[i]
            notes = []

            if slide_info.get("title"):
                notes.append(f"Title: {slide_info['title']}")

            if slide_info.get("subtitle"):
                notes.append(f"Subtitle: {slide_info['subtitle']}")

            if slide_info.get("key_points"):
                notes.append("Key Points:")
                for point in slide_info["key_points"]:
                    notes.append(f"  • {point}")

            if slide_info.get("speaker_notes"):
                notes.append(f"\n{slide_info['speaker_notes']}")

            if notes:
                notes_slide = slide.notes_slide
                text_frame = notes_slide.notes_text_frame
                if text_frame is not None:
                    text_frame.text = "\n".join(notes)

    # Save presentation
    prs.save(output_file)

    return f"Successfully generated presentation with {len(slide_images)} slides to {output_file}"


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate PowerPoint presentation from slide images"
    )
    parser.add_argument(
        "--plan-file",
        required=True,
        help="Absolute path to JSON presentation plan file",
    )
    parser.add_argument(
        "--slide-images",
        nargs="+",
        required=True,
        help="Absolute paths to slide images in order (space-separated)",
    )
    parser.add_argument(
        "--output-file",
        required=True,
        help="Output path for generated PPTX file",
    )

    args = parser.parse_args()

    try:
        print(
            generate_ppt(
                args.plan_file,
                args.slide_images,
                args.output_file,
            )
        )
    except Exception as e:
        print(f"Error while generating presentation: {e}")
